name: pitch_detector_plus_web
description: This library can be used to detect pitch from mic stream in web
version: 0.0.6
homepage: https://github.com/gangadharashettypj/pitch_detector/tree/master/pitch_detector_web

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: ">=2.5.0"

flutter:
  plugin:
    platforms:
      web:
        pluginClass: PitchDetectorPlusWeb
        fileName: pitch_detector_plus_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  pitch_detector_plus_platform_interface: 0.0.5

