name: pitch_detector_web
version: 0.0.1

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: ">=2.5.0"

flutter:
  plugin:
    platforms:
      web:
        pluginClass: PitchDetectorPlugin
        fileName: pitch_detector_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

