name: pitch_detector_platform_interface
description: A common platform detect pitch
version: 0.0.1


environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: 2.1.3
